[package]
name = "kvs"
version = "0.1.0"
authors = ["TangliziGit <tanglizimail@foxmail.com>"]
description = "A key-value store"
edition = "2018"

[dependencies]

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
